import format

def get_state_from_slug(slug):
    """Return a country from a slug we pass in"""
    for state in STATES:
        if format.slugify(state[1]) == slug:
            return state
        
def get_country_from_slug(slug):
    """Return a country from a slug we pass in"""
    for country in COUNTRIES:
        if format.slugify(country[1]) == slug:
            return country

COUNTRIES = (
    ('US', 'United States'),
)

STATES = (
    ('AK', 'Alaska'),
    ('AL', 'Alabama'),
    ('AR', 'Arkansas'),
    ('AZ', 'Arizona'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DC', 'District of Columnbia'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('IA', 'Iowa'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('MA', 'Massachusetts'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MO', 'Missouri'),
    ('MS', 'Mississippi'),
    ('MT', 'Montana'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('NE', 'Nebraska'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NV', 'Nevada'),
    ('NY', 'New York'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VI', 'Virginia'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
)


CODES = {'AK': ['ANC',
        'ANI',
        'BRW',
        'BET',
        'KCL',
        'KCG',
        'CDV',
        'DLG',
        'DUT',
        'EDF',
        'FAI',
        'GAL',
        'GLV',
        'HNS',
        'HOM',
        'HNH',
        'HPB',
        'ILI',
        'JNU',
        'ENA',
        'KTN',
        'AKN',
        'ADQ',
        'OTZ',
        'OME',
        'PSG',
        'PIP',
        'PHO',
        'SIT',
        'VDZ',
        'YAK'],
 'AL': ['ANB', 'BHM', 'DHN', 'GAD', 'HSV', 'MOB', 'MGM', 'MSL', 'TCL'],
 'AR': ['ELD',
        'XNA',
        'FYV',
        'FSM',
        'HRO',
        'HOT',
        'JBR',
        'LIT',
        'WMH',
        'ROG',
        'SPZ',
        'TXK'],
 'AZ': ['IFP',
        'CTW',
        'FLG',
        'FHU',
        'GCN',
        'IGM',
        'HII',
        'MSC',
        'PGA',
        'PJB',
        'PHX',
        'PRC',
        'SCF',
        'SDX',
        'SOW',
        'TUS',
        'INW',
        'YUM'],
 'CA': ['ACV',
        'BFL',
        'BJC',
        'BUR',
        'CLD',
        'CIC',
        'CCR',
        'CEC',
        'EDW',
        'SUU',
        'FAT',
        'IPL',
        'IYK',
        'TVL',
        'LPC',
        'LGB',
        'LAX',
        'MMH',
        'MHR',
        'MCE',
        'MOD',
        'MRY',
        'OAK',
        'ONT',
        'OXR',
        'PSP',
        'PMD',
        'PRB',
        'RDD',
        'RAL',
        'SAC',
        'SMF',
        'SQL',
        'SAN',
        'SFO',
        'SJC',
        'SBP',
        'SNA',
        'SBA',
        'SMX',
        'SMO',
        'STS',
        'SCK',
        'TKF',
        'TNP',
        'UKI',
        'VNY',
        'VIS',
        'WVI'],
 'CO': ['ALS',
        'ASE',
        'COS',
        'CEZ',
        'DEN',
        'DRO',
        'FNL',
        'GJT',
        'GUC',
        'HDN',
        'MTJ',
        'PGO',
        'PUB',
        'RIL',
        'TEX',
        'EGE'],
 'CT': ['BDR', 'BDL', 'HVN', 'GON', 'OXC'],
 'DC': ['DCA', 'IAD'],
 'DE': ['ILG'],
 'FL': ['BCT',
        'PIE',
        'DAB',
        'FLL',
        'RSW',
        'FMY',
        'GNV',
        'HST',
        'JAX',
        'EYW',
        'ISM',
        'LAL',
        'LEE',
        'MTH',
        'MLB',
        'MIA',
        'OPF',
        'TMB',
        'APF',
        'OCF',
        'MCO',
        'SFB',
        'PFN',
        'PNS',
        'PGD',
        'SRQ',
        'COF',
        'UST',
        'SUA',
        'TLH',
        'TPA',
        'VPS',
        'VNC',
        'VRB',
        'PBI'],
 'GA': ['ABY',
        'AHN',
        'ATL',
        'PDK',
        'AGS',
        'BQK',
        'CSG',
        'LGC',
        'MCN',
        'SAV',
        'SSI',
        'VLD'],
 'HI': ['HNM',
        'ITO',
        'HIK',
        'HNL',
        'MKK',
        'OGG',
        'JHM',
        'LIH',
        'KOA',
        'LNY',
        'HPV'],
 'IA': ['BRL', 'CID', 'DSM', 'DBQ', 'FOD', 'IOW', 'MCW', 'SUX', 'ALO'],
 'ID': ['BOI', 'COE', 'IDA', 'LWS', 'PIH', 'SUN', 'TWF'],
 'IL': ['BLV',
        'BMI',
        'CMI',
        'MDW',
        'ORD',
        'DEC',
        'MWA',
        'MLI',
        'PIA',
        'UIN',
        'RFD',
        'SPI',
        'AUZ',
        'PWK'],
 'IN': ['BMG', 'EVV', 'FWA', 'GYY', 'IND', 'LAF', 'MIE', 'SBN', 'HUF'],
 'KS': ['DDC', 'GCK', 'HYS', 'LBL', 'MHK', 'SLN', 'ICT', 'WIC'],
 'KY': ['LEX', 'LOU', 'SDF', 'OWB', 'PAH'],
 'LA': ['AEX', 'BTR', 'LFT', 'LCH', 'MLU', 'MSY', 'SHV'],
 'MA': ['BED', 'BOS', 'CEF', 'HYA', 'MVY', 'ACK', 'EWB', 'OWD', 'PVC', 'ORH'],
 'MD': ['ANP', 'BWI', 'ADW', 'ESN', 'FDK', 'HGR', 'SBY'],
 'ME': ['LEW',
        'AUG',
        'BGR',
        'BHB',
        'HUL',
        'PWM',
        'PQI',
        'RKD',
        'SFM',
        'WVL',
        'ISS'],
 'MI': ['APN',
        'ARB',
        'YIP',
        'BEH',
        'CAD',
        'DTW',
        'ESC',
        'FNT',
        'GLR',
        'GRR',
        'CMX',
        'IMT',
        'IWD',
        'JXN',
        'AZO',
        'LAN',
        'MBL',
        'MQT',
        'MNM',
        'MBS',
        'MKG',
        'PLN',
        'PTK',
        'CIU',
        'TVC'],
 'MN': ['BJI',
        'BRD',
        'DLH',
        'SUW',
        'GPZ',
        'HIB',
        'INL',
        'MML',
        'MSP',
        'RST',
        'STC',
        'TVF'],
 'MO': ['CGI', 'COU', 'TBN', 'JEF', 'JLN', 'MKC', 'MCI', 'IRK', 'SGF', 'STL'],
 'MS': ['GTR', 'GLH', 'GPT', 'JAN', 'PIB', 'MEI', 'TUP'],
 'MT': ['BIL',
        'BZN',
        'BTM',
        'GGW',
        'GDV',
        'GTF',
        'HVR',
        'HLN',
        'FCA',
        'LWT',
        'MLS',
        'MSO',
        'WYS'],
 'NC': ['AVL',
        'CLT',
        'RDU',
        'RWI',
        'FAY',
        'PGV',
        'HKY',
        'GSO',
        'OAJ',
        'ISO',
        'SOP',
        'EWN',
        'ILM',
        'INT'],
 'ND': ['BIS', 'DIK', 'FAR', 'GFK', 'JMS', 'MOT', 'ISN'],
 'NE': ['AIA',
        'CDR',
        'OLU',
        'GRI',
        'EAR',
        'LNK',
        'MCK',
        'OFK',
        'LBF',
        'OMA',
        'BFF'],
 'NH': ['LCI', 'LEB', 'MHT', 'ASH', 'PSM'],
 'NJ': ['ACY', 'AIY', 'CDW', 'MMU', 'EWR', 'PCT', 'TTN', 'WRI'],
 'NM': ['ALM',
        'ABQ',
        'CNM',
        'CVN',
        'FMN',
        'GUP',
        'HOB',
        'LRU',
        'LAM',
        'ROW',
        'RUI',
        'SAF',
        'TSM'],
 'NV': ['CSN',
        'EKO',
        'ELY',
        'FLX',
        'NFL',
        'VGT',
        'LAS',
        'HSH',
        'MEV',
        'RNO',
        'WMC'],
 'NY': ['ALB',
        'BGM',
        'BUF',
        'ELM',
        'HTO',
        'FRG',
        'ISP',
        'ITH',
        'JHW',
        'MSS',
        'LGA',
        'JFK',
        'SWF',
        'IAG',
        'OGS',
        'PLB',
        'ROC',
        'SLK',
        'SYR',
        'UCA',
        'ART',
        'HPN'],
 'OH': ['CAK',
        'CVG',
        'LUK',
        'CLE',
        'CMH',
        'LCK',
        'DAY',
        'AOH',
        'PKB',
        'TOL',
        'YNG'],
 'OK': ['BVO', 'WDG', 'LAW', 'OKC', 'PNC', 'SWO', 'TUL'],
 'OR': ['EUG', 'HIO', 'LMT', 'MFR', 'OTH', 'PDT', 'PDX', 'RDM', 'SLE'],
 'PA': ['ABE',
        'AOO',
        'BFD',
        'CTH',
        'DUJ',
        'ERI',
        'FKL',
        'HAR',
        'MDT',
        'JST',
        'LNS',
        'LBE',
        'PHL',
        'PIT',
        'RDG',
        'SCE',
        'AVP',
        'IPT'],
 'RI': ['PVD', 'WST'],
 'SC': ['BFT', 'CHS', 'CAE', 'FLO', 'GSP', 'HVS', 'HHH', 'MYR'],
 'SD': ['ABR', 'BKX', 'HON', 'PIR', 'RAP', 'FSD', 'ATY'],
 'TN': ['CHA', 'MKL', 'TRI', 'TYS', 'MEM', 'BNA'],
 'TX': ['ABI',
        'AMA',
        'BZT',
        'AUS',
        'BPT',
        'BRO',
        'CLL',
        'CRP',
        'DAL',
        'DFW',
        'DRT',
        'ELP',
        'FTW',
        'HRL',
        'EFD',
        'SGR',
        'IAH',
        'HOU',
        'GGG',
        'ILE',
        'GRK',
        'LRD',
        'LBB',
        'ASL',
        'MFE',
        'MAF',
        'PRX',
        'SJT',
        'SAT',
        'TPL',
        'TYR',
        'UVA',
        'VCT',
        'ACT',
        'SPS'],
 'UT': ['CDC', 'CNY', 'OGD', 'PVU', 'SGU', 'SLC', 'VEL'],
 'VA': ['OFP',
        'CHO',
        'DAN',
        'LYH',
        'MNZ',
        'PHF',
        'ORF',
        'RIC',
        'ROA',
        'SHD',
        'WGO'],
 'VI': ['MEL', 'MQL'],
 'VT': ['BTV', 'RUT', 'WRJ'],
 'WA': ['BLI',
        'BME',
        'PAE',
        'EXM',
        'FRD',
        'MWH',
        'ODW',
        'OLM',
        'PBO',
        'PSC',
        'PER',
        'CLM',
        'PUW',
        'SEA',
        'GEG',
        'ALW',
        'EAT',
        'YKM'],
 'WI': ['ATW',
        'EAU',
        'GRB',
        'LSE',
        'MSN',
        'MKE',
        'OSH',
        'RHI',
        'SBM',
        'STE',
        'CWA'],
 'WY': ['CPR', 'CYS', 'GCC', 'JAC', 'LAR', 'RIW', 'RKS', 'SHR', 'WRL', 'COD']}

